import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {parseDate,TZ,occurrence} from '../public/calendar.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function buildPages(data,base,version){
const dateLabel=e=>new Intl.DateTimeFormat('es-MX',{timeZone:TZ,dateStyle:'long',...(e.start.length>10?{timeStyle:'short'}:{})}).format(parseDate(e.start));
const upcoming=data.events.map(e=>occurrence(e)).filter(e=>e&&e.status!=='Cancelada').sort((a,b)=>parseDate(a.start)-parseDate(b.start));
const monthly=upcoming.find(e=>e.type==='Retiro mensual'),semester=upcoming.find(e=>e.type==='Retiro semestral');
const original=await readFile('public/index.html','utf8');
const section=id=>original.match(new RegExp(`<section[^>]*id="${id}"[\\s\\S]*?</section>`))[0];
const dialogs=original.slice(original.indexOf('<dialog'),original.indexOf('<noscript'));
const link=(path,label)=>`<a href="${base}${path}/">${label}<span aria-hidden="true">↗</span></a>`;
const intro=(label,title,description)=>`<section class="page-intro"><span class="eyebrow">${label}</span><h1 class="page-title"><span class="word-mask"><span>${title}</span></span></h1><p>${description}</p></section>`;
const block=(title,body)=>`<article class="info-block reveal"><h2>${title}</h2><div>${body}</div></article>`;
const p=s=>`<p>${s}</p>`;
const cta=`<div class="page-cta"><h2>¿Te sumas?</h2><a class="button signup" href="#">Me interesa participar ↗</a><p>El equipo confirma los detalles contigo después de recibir tu solicitud.</p></div>`;
const nav=[['agenda','Agenda'],['actividades','Actividades'],['recursos','Recursos'],['participar','Participar']];
async function page(path,title,description,body,active=''){
body=body.replace('<p>Cargando la agenda…</p>',data.events.map(e=>`<article class="event-card"><div class="event-info"><span class="badge">${esc(e.type)}</span><h3><a href="${base}eventos/${esc(e.id)}/">${esc(e.title)}</a></h3><p>${esc(dateLabel(e))} · ${esc(e.location)}</p></div></article>`).join('')).replace('<div id="resources-list" class="resources-grid"></div>',`<div id="resources-list" class="resources-grid">${data.resources.map((r,i)=>`<a class="resource-card" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer"><span class="resource-symbol">${i+1}</span><div><small>${esc(r.category)}</small><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p></div><span>↗</span></a>`).join('')}</div>`);
const depth=path.split('/').filter(Boolean).length;
let html=`<!doctype html><html lang="es-MX"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#173fe5"><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)} · La Comarca"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:image" content="https://jadrk040507.github.io/comarca/assets/lighthouse.webp"><title>${esc(title)} · La Comarca</title><link rel="icon" href="${base}assets/favicon.svg"><link rel="manifest" href="${base}manifest.webmanifest"><link rel="stylesheet" href="${base}styles.css?v=${version}"><script type="module" src="${base}app.js?v=${version}"></script></head><body><div class="scroll-progress" aria-hidden="true"></div><a class="skip" href="#contenido">Ir al contenido</a><header class="header"><a class="brand" href="${base}" aria-label="La Comarca, inicio">LC<span class="brand-dot">.</span></a><nav aria-label="Navegación principal">${nav.map(([key,label])=>`<a href="${base}${key}/" ${active===key?'aria-current="page"':''}>${label}</a>`).join('')}</nav><button class="icon-button notification-trigger">Avisos ↗</button></header><main id="contenido">${path?`<div class="breadcrumbs"><a href="${base}">Inicio</a><span>/</span>${depth>1?`<a href="${base}${path.startsWith('eventos')?'agenda':'actividades'}/">${path.startsWith('eventos')?'Agenda':'Actividades'}</a><span>/</span>`:''}<span>${esc(title)}</span></div>`:''}${body}</main><footer class="footer"><div class="footer-top"><p>Formación. Amistad. Servicio.</p><div>${link('nosotros','La Comarca')}${link('ayuda','Preguntas frecuentes')}${link('avisos','Calendario y avisos')}${link('participar','Participar')}</div></div><a class="footer-wordmark" href="${base}">LA COMARCA.</a><small id="updated"></small><p class="footer-note">Consulta pública · La organización, los datos de alumnos y las solicitudes de participación se gestionan de forma privada.</p></footer>${dialogs}</body></html>`;
html=html.replaceAll('class="signup" href="#"','class="signup" href="https://la-comarca.notion.site/1b7057bc38f142a48d7cbe55dba73a0e"').replaceAll('signup" href="#"','signup" href="https://la-comarca.notion.site/1b7057bc38f142a48d7cbe55dba73a0e"');
html=html.replaceAll('src="./assets/',`src="${base}assets/`).replaceAll('href="#agenda"',`href="${base}agenda/"`).replaceAll('href="#primera-vez"',`href="${base}participar/"`);
await mkdir(`dist/${path}`,{recursive:true});await writeFile(`dist/${path?path+'/':''}index.html`,html);
}
const homeHero=original.match(/<section class="hero">[\s\S]*?<\/section>/)[0];
await page('','Un lugar para encontrarnos','Formación, amistad y servicio. Encuentra tu próximo plan en La Comarca.',homeHero+`<section class="section home-directory"><span class="eyebrow">EXPLORA LA COMARCA</span><h2>Cada plan,<br>su espacio.</h2><div class="directory-links">${nav.map(([path,label],i)=>`<a href="${base}${path}/"><small>0${i+1}</small><h3>${label}</h3><p>${['Fechas, sedes y encuentros.','Conoce lo que hacemos y cómo sumarte.','Lecturas y propuestas para rezar.','Tu primer encuentro empieza aquí.'][i]}</p><span>↗</span></a>`).join('')}</div></section><section class="section home-feature"><div><span class="eyebrow">EN LA AGENDA</span><h2>Una pausa.<br>Un encuentro.</h2><p>${monthly?esc(dateLabel(monthly))+' · '+esc(monthly.location)+'. '+esc(monthly.summary):'Consulta los próximos encuentros en la agenda.'}</p>${monthly?link('eventos/'+monthly.id,'Ver el retiro mensual'):link('agenda','Ver la agenda')}</div><a href="${base}${monthly?'eventos/'+monthly.id+'/':'agenda/'}"><img src="${monthly?.image?esc(monthly.image):base+'assets/lighthouse.webp'}" alt="${monthly?.image?'Invitación del retiro mensual':'Faro junto al mar'}" loading="lazy" width="1122" height="1402"></a></section>`);
await page('agenda','Agenda','Consulta fechas, sedes y horarios de los encuentros de La Comarca.',intro('ENCUENTROS','Nos vemos.','Encuentra un espacio en tu semana. Cada encuentro tiene una ficha propia con la información para participar.')+section('agenda')+block('Antes de salir.',p('Los círculos muestran su próxima fecha según el horario semanal habitual. Confirma la sesión: puede cambiar por vacaciones o por actividades de la sede.')+p('Las actividades marcadas «Por confirmar» todavía tienen detalles provisionales. Todos los horarios corresponden a Ciudad de México.')+link('avisos','Calendario y recordatorios')),'agenda');
const programs=[
['circulos','Círculos','Formación para la vida cotidiana. Un encuentro breve y habitual para profundizar en la fe.',[
['Un espacio cada semana.',p('Puedes elegir el horario que se ajuste a tu semana. Si quieres conocer un círculo o cambiar de grupo, indícalo al equipo en el formulario de participación.')],
['Horarios habituales.',`<dl class="schedule-list"><dt>Miércoles · 15:00</dt><dd>Ciudad UP · Sala de Colores.</dd><dt>Jueves · 10:00</dt><dd>Anáhuac Norte · Iglesia de Sedes Sapientiae.</dd><dt>Sábado · 12:00</dt><dd>Sede por confirmar con el equipo.</dd></dl>`+p('Confirma la sesión antes de trasladarte. Consulta las próximas fechas en la agenda.')],
['Para aprovecharlo.',p('Lleva tus preguntas y algo para anotar. Después puedes volver a las ideas del encuentro y buscar una manera concreta de vivirlas durante la semana.')+`<a href="https://opusdei.org/es/article/el-circulo-empieza-cuando-acaba-como-aprovechar-mejor-el-circulo/" target="_blank" rel="noopener noreferrer">Lectura: cómo aprovechar mejor el círculo ↗</a>`]]],
['retiros','Retiros','Hacer una pausa para rezar, reflexionar y volver a lo cotidiano con perspectiva.',[
['Retiro mensual.',p(monthly?esc(dateLabel(monthly))+'. '+esc(monthly.summary):'Un encuentro con meditación y charla. Consulta las próximas fechas en la agenda.')+(monthly?link('eventos/'+monthly.id,'Consultar la invitación'):link('agenda','Consultar agenda'))],
['Retiro semestral.',p(semester?esc(dateLabel(semester))+'. '+esc(semester.summary):'Una estancia fuera para la oración y la reflexión. Consulta las próximas fechas y los detalles con el equipo.')+(semester?link('eventos/'+semester.id,'Ver la ficha del retiro'):link('agenda','Consultar agenda'))],
['Cómo prepararte.',p('Confirma tu participación y la ubicación. Para una estancia fuera, espera las indicaciones del equipo sobre equipaje, horarios y punto de salida. Si necesitas coche o puedes ofrecer lugares, coméntalo al organizar el traslado.')+link('recursos','Recursos para rezar')]]],
['catecismo','Catecismo','Comparte tu tiempo como voluntario en la comunidad de Los Conejos.',[
['La mañana del sábado.',`<ol class="timeline"><li><strong>09:30</strong><span>Salida prevista de Santo María.</span></li><li><strong>10:00–11:00</strong><span>Catecismo en Los Conejos.</span></li><li><strong>11:30–12:00</strong><span>Regreso previsto a Santo María.</span></li></ol>`+p('Este horario es provisional. Confirma el día, tu turno y el traslado con el equipo antes de salir.')],
['Tu turno y tu tema.',p('Selecciona Catecismo en el formulario. El equipo coordina qué catequistas participan cada día, el tema que prepara cada uno y los materiales que harán falta. No es necesario que todos vayan cada sábado.')],
['Preparar la sesión.',p('Antes de tu turno, acuerda el objetivo de la clase, revisa el guion y prepara una actividad adecuada para el grupo. Los guiones y archivos de trabajo se comparten con los catequistas dentro del espacio privado.')],
['Un espacio cuidado.',p('La lista de alumnos, asistencia, calificaciones y seguimiento se consultan únicamente en la gestión interna. No se publican nombres, expedientes ni fotografías de los alumnos en este portal.')]]],
['convivencias','Convivencias','Deporte, excursiones y tiempo juntos en distintos lugares.',[
['Un plan para compartir.',p('Las convivencias son encuentros para hacer deporte y convivir. También puede haber hikes, visitas culturales, asados y planes entre amigos. Las fechas se anunciarán cuando estén definidas.')],
['Organizar una salida.',p('La ficha de cada salida reunirá fecha y lugar. Para las actividades fuera, el equipo confirmará punto de encuentro, hora de regreso, coches disponibles y contribución, si la hay.')+p('Al apuntarte, comenta si necesitas transporte o puedes ofrecer lugares. Los acuerdos sobre conductores, casetas y gastos se organizan con los participantes de forma privada.')],
['Antes de confirmar.',p('Pregunta qué necesitas llevar, qué incluye la actividad y si hay un cupo o una fecha límite. Por ahora no hay una convivencia con fecha confirmada en la agenda pública.')]]],
['servicio','Servicio','Pequeñas acciones concretas: tiempo, compañía y ayuda.',[
['Distintas formas de ayudar.',p('Además del catecismo, se organizan despensas y visitas. Puedes ofrecer tiempo para preparar una actividad, colaborar en la logística o participar el día de la salida.')],
['Empieza por tu disponibilidad.',p('En el formulario selecciona la actividad que te interesa o solicita información sobre otros planes. El equipo te orientará sobre las necesidades y las próximas fechas.')],
['Catecismo en Los Conejos.',p('Es la actividad de servicio con sesiones previstas actualmente. Consulta el horario provisional y la forma de sumarte como catequista.')+link('actividades/catecismo','Conocer catecismo')]]]
];
await page('actividades','Actividades','Círculos, retiros, catecismo, convivencias y servicio en La Comarca.',intro('FORMACIÓN / AMISTAD / SERVICIO','A tu ritmo.','Puedes venir a un encuentro, sumarte a una salida o colaborar en un proyecto. Aquí encontrarás qué es cada actividad y cómo participar.')+`<section class="section program-directory">${programs.map(([slug,title,desc],i)=>`<a class="program-row reveal" href="${base}actividades/${slug}/"><small>0${i+1}</small><h2>${title}</h2><p>${desc}</p><span>↗</span></a>`).join('')}</section>`,'actividades');
for(const [slug,title,desc,blocks] of programs)await page(`actividades/${slug}`,title,desc,intro('ACTIVIDADES',title+'.',desc)+blocks.map(([t,b])=>block(t,b)).join('')+`<div class="section related-links">${link('agenda','Próximas fechas')}${link('actividades','Todas las actividades')}</div>`+cta,'actividades');
await page('recursos','Recursos','Lecturas de Youth y recursos oficiales para la oración y la formación.',intro('LECTURAS / ORACIÓN / FORMACIÓN','Ideas que quedan.','Una selección para acompañar los encuentros y seguir profundizando por tu cuenta. Los textos y las descargas se abren en su fuente oficial.')+section('recursos')+block('Para un retiro.',p('Puedes explorar las propuestas de retiro mensual y preparar un rato de oración. El «Parón del mes» de la selección corresponde a septiembre; no implica que sea el material elegido para el retiro local de octubre.')+`<a href="https://opusdei.org/es/tag/retiro-mensual/" target="_blank" rel="noopener noreferrer">Propuestas de retiro mensual ↗</a>`)+block('Para los catequistas.',p('Los temas de clase, guiones y materiales de trabajo se coordinan dentro del espacio privado de catecismo. Si vas a colaborar, pide acceso al equipo después de confirmar tu participación.')+link('actividades/catecismo','Cómo colaborar en catecismo')),'recursos');
await page('participar','Participar','Cómo apuntarte a una actividad de La Comarca y qué ocurre después.',intro('TU PRIMER ENCUENTRO','Empieza por uno.','No necesitas conocer el Opus Dei ni tener una cuenta de Notion. Puedes pedir información o elegir una actividad concreta.')+block('01 / Elige un plan.',p('Consulta su fecha, sede y estado en la agenda. Si aún no sabes cuál elegir, conoce primero las actividades o pregunta al equipo.')+link('agenda','Explorar la agenda'))+block('02 / Cuéntanos.',p('Abre el formulario de participación y escribe tu nombre, correo y la actividad que te interesa. Puedes solicitar novedades y, si lo deseas, facilitar un contacto de WhatsApp con tu autorización.')+`<a class="button signup" href="#">Abrir formulario de participación ↗</a>`)+block('03 / Confirma los detalles.',p('El envío del formulario es una solicitud, no una reserva automática. El equipo revisa tu interés y confirma contigo la participación, la ubicación y lo que necesites saber antes de acudir.'))+block('Si la actividad es fuera.',p('Para retiros o convivencias fuera, pregunta por transporte, alojamiento y contribución antes de confirmar. Los importes y las instrucciones se comparten para esa actividad concreta; este portal no cobra una suscripción.'))+block('Tu información.',p('El formulario se abre en Notion. Las respuestas son privadas y las consulta el equipo organizador para coordinar tu participación. No escribas datos de alumnos ni adjuntes expedientes en la solicitud pública.')+p('Los avisos son opcionales. Las notificaciones web y los envíos automáticos aún están en preparación.')+link('ayuda','Resolver otras dudas')),'participar');
await page('nosotros','La Comarca','Un punto de encuentro para la formación, la amistad y el servicio.',intro('LA COMARCA','Un punto de encuentro.','Formación cristiana, amistad y oportunidades para dedicar tiempo a los demás.')+`<div class="about-image"><img src="${base}assets/lighthouse.webp" alt="Faro junto al mar, imagen simbólica de La Comarca" width="1672" height="941"></div>`+block('Lo que nos reúne.',p('En torno a La Comarca se organizan círculos, retiros, tertulias, convivencias y actividades de servicio. Este portal permite conocer los planes y participar según tus intereses y disponibilidad.'))+block('Conocer San Rafael.',p('Los círculos y el retiro mensual anunciados forman parte de la labor de San Rafael. Puedes conocer más sobre la formación para jóvenes en la web oficial del Opus Dei.')+`<a href="https://opusdei.org/es/page/san-rafael/" target="_blank" rel="noopener noreferrer">La labor de San Rafael ↗</a>`)+block('Encontrarnos.',p('Las actividades tienen distintas sedes: La Comarca, Ciudad UP, Anáhuac Norte y Los Conejos, entre otras. La sede aparece en cada ficha. Pide la ubicación exacta a quien te invitó o al equipo al confirmar tu participación.'))+cta);
await page('ayuda','Preguntas frecuentes','Resuelve dudas sobre participación, sedes, transporte, recursos y avisos.',intro('INFORMACIÓN PRÁCTICA','Antes de venir.','Las respuestas para dar el siguiente paso con claridad.')+section('primera-vez').replace(/<div class="welcome-copy[\s\S]*?<\/div>/,'')+block('¿Tiene costo participar?',p('Este portal no funciona con una suscripción. En retiros o convivencias fuera puede haber una contribución por gastos de la actividad. Consulta con el equipo el importe y qué incluye; no hay un cobro general ni se piden comprobantes para todos los planes.'))+block('¿Cómo consigo un ride?',p('Después de solicitar tu participación, comenta al equipo si necesitas un lugar en un coche o si puedes llevar a otros. Confirma punto de salida, hora, regreso y cualquier gasto compartido.'))+block('¿Dónde encuentro materiales?',p('Las lecturas públicas están en Recursos y enlazan a las fuentes oficiales. Los guiones de catecismo y documentos de organización se comparten de forma privada con quienes colaboran.')+link('recursos','Ir a recursos'))+block('¿Se actualiza mi calendario solo?',p('El archivo descargado importa fechas; no es una suscripción automática. Si cambia un evento, consulta la web y actualiza tu calendario. Revisa posibles duplicados al volver a importar.')+link('avisos','Calendario y avisos')));
await page('avisos','Calendario y avisos','Opciones disponibles para guardar fechas y seguir las novedades de La Comarca.',intro('MANTENTE AL TANTO','No perder el plan.','Consulta la agenda y guarda las fechas que te interesan. Aquí puedes revisar qué opciones de avisos están disponibles.')+block('Tu calendario.',p('Descarga la agenda completa o guarda un encuentro desde su ficha. Importa el archivo .ics en tu aplicación de calendario y configura allí el recordatorio que prefieras.')+`<a class="button" href="${base}agenda.ics" download>Descargar agenda ↗</a>`+p('La descarga no crea una suscripción: los cambios posteriores no se reflejan solos. Los círculos incluyen su recurrencia semanal. Confirma las sesiones antes de acudir.'))+block('Avisos en el celular.',p('La entrega de notificaciones web todavía está en preparación. Cuando esté disponible, podrás activarla voluntariamente para este dispositivo. No es necesario permitir avisos para consultar el sitio.')+`<button class="button notification-trigger">Ver opciones del dispositivo ↗</button>`)+block('Correo y WhatsApp.',p('Puedes indicar en el formulario si quieres recibir novedades por correo o facilitar WhatsApp con tu autorización. Los envíos automáticos todavía no están activos; enviar el formulario no activa una confirmación automática por WhatsApp.')+`<a class="button signup" href="#">Abrir formulario ↗</a>`)+block('A mano en tu celular.',p('Puedes añadir esta web a la pantalla de inicio desde el menú de tu navegador. En Safari para iPhone, utiliza Compartir → Añadir a pantalla de inicio. Así tendrás un acceso directo a la agenda.')));
for(const e of data.events){
const date=new Intl.DateTimeFormat('es-MX',{timeZone:TZ,dateStyle:'full',...(e.start.length>10?{timeStyle:'short'}:{})}).format(parseDate(e.start));
const detail=`<section class="section event-page"><div><span class="eyebrow">${esc(e.type)}${e.status?' / '+esc(e.status):''}</span><h1 class="event-page-title">${esc(e.title)}</h1><p class="event-description">${esc(e.summary)}</p><dl class="event-facts"><dt>${e.recurrence==='Semanal'?'Horario habitual desde':'Fecha'}</dt><dd>${esc(date)}${e.end?' — '+esc(new Intl.DateTimeFormat('es-MX',{timeZone:TZ,dateStyle:'long',...(e.end.length>10?{timeStyle:'short'}:{})}).format(parseDate(e.end))):''}</dd><dt>Sede</dt><dd>${esc(e.location||'Por confirmar')}</dd><dt>Zona horaria</dt><dd>Ciudad de México</dd>${e.recurrence==='Semanal'?'<dt>Frecuencia</dt><dd>Semanal · confirma la sesión antes de acudir.</dd>':''}</dl><div class="detail-actions">${e.status==='Cancelada'?'':`<a class="button signup" href="#">Me interesa participar ↗</a>`}<button class="button" data-calendar-id="${esc(e.id)}">Guardar en mi calendario ↓</button></div><p class="small">El formulario es una solicitud. El equipo confirma tu participación.</p></div>${e.image?`<img class="event-poster" src="${esc(e.image)}" alt="Invitación de ${esc(e.title)}">`:`<aside class="event-aside"><span class="eyebrow">LA COMARCA</span><p>Un espacio<br>en tu semana.</p><a href="${base}participar/">Cómo participar ↗</a></aside>`}</section>`;
await page(`eventos/${e.id}`,e.title,e.summary,detail+block('Antes de acudir.',p(e.type==='Retiro semestral'?'Costo, alojamiento y transporte pendientes de confirmar. No des por reservado tu lugar hasta recibir la confirmación del equipo.':e.type==='Catecismo'?'El horario de catecismo y los traslados son provisionales. Confirma tu turno y el tema que prepararás con el equipo.':'Confirma la sesión y pide la ubicación exacta si no conoces la sede. Puedes plantear tus dudas al equipo cuando revise tu solicitud.'))+`<div class="section related-links">${link('agenda','Volver a la agenda')}${link('ayuda','Información práctica')}</div>`,'agenda');
}
await page('404','Página no encontrada','La página solicitada no está disponible.',intro('404','Por aquí no era.','Puedes volver a la agenda o explorar las actividades para encontrar lo que buscas.')+`<div class="section related-links">${link('agenda','Ir a la agenda')}${link('actividades','Ver actividades')}</div>`);await writeFile('dist/404.html',await readFile('dist/404/index.html'));
console.log(`Sitio completo: 8 páginas principales, ${programs.length} actividades y ${data.events.length} fichas de eventos.`);
}
