import {writeFile,mkdir,readFile,rename,rm} from 'node:fs/promises';
import {eventFromPage,resourceFromPage} from './notion-model.mjs';
const token=process.env.NOTION_TOKEN;
if(!token){if(process.argv.includes('--allow-snapshot')){console.log('Notion no está conectado: se usa la edición pública revisada.');process.exit(0);}throw Error('Falta NOTION_TOKEN. No se publica una sincronización incompleta.');}
const agenda=process.env.NOTION_AGENDA_ID,materials=process.env.NOTION_MATERIALS_ID;
if(![agenda,materials].every(x=>/^[a-f0-9-]{32,36}$/i.test(x||'')))throw Error('Faltan los identificadores de las fuentes de datos de Notion.');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function api(path,body){for(let attempt=0;attempt<5;attempt++){await delay(350);let r;try{r=await fetch('https://api.notion.com/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,'Notion-Version':'2025-09-03','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(30000)});}catch{if(attempt===4)throw Error('Notion no responde; se conserva la web publicada.');await delay(1000*2**attempt);continue;}if(r.ok)return r.json();if(r.status===429||r.status>=500){await delay(Math.min(30000,Math.max(1000,Number(r.headers.get('retry-after')||2**attempt)*1000)));continue;}throw Error(`Notion respondió HTTP ${r.status}. Revisa conexión, permisos y propiedades.`);}throw Error('Notion no está disponible; se conserva la web publicada.');}
async function query(id){const schema=await api('data_sources/'+id);if(schema.properties?.['Publicar en web']?.type!=='checkbox')throw Error('La fuente necesita la casilla Publicar en web.');let cursor,out=[];do{const r=await api('data_sources/'+id+'/query',{page_size:100,filter:{property:'Publicar en web',checkbox:{equals:true}},...(cursor?{start_cursor:cursor}:{})});out.push(...r.results);cursor=r.has_more?r.next_cursor:null;if(r.has_more&&!cursor)throw Error('Paginación incompleta de Notion.');if(out.length>10000)throw Error('Demasiados registros públicos.');}while(cursor);return out;}
const allowedImageHosts=new Set(['prod-files-secure.s3.us-west-2.amazonaws.com','s3.us-west-2.amazonaws.com','secure.notion-static.com','file.notion.so']);
const staging='public/.generated-next';await rm(staging,{recursive:true,force:true});await mkdir(staging,{recursive:true});
async function image(page,id){const file=page.properties?.['Imagen pública']?.files?.[0];if(!file)return id==='3d579aad5d8380d3a081fa12c961d5d6'?'./assets/retiro-octubre.webp':null;const url=file.file?.url||file.external?.url;if(!url)throw Error('Imagen pública sin URL.');const u=new URL(url);if(u.protocol!=='https:'||!allowedImageHosts.has(u.hostname))throw Error('Sube la imagen a Imagen pública en Notion; no se descargan servidores externos.');const r=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('No se pudo descargar una imagen pública.');const types={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/gif':'gif'},ext=types[(r.headers.get('content-type')||'').split(';')[0]];if(!ext)throw Error('Formato de imagen no admitido.');const chunks=[];let size=0;for await(const chunk of r.body){size+=chunk.length;if(size>10*1024*1024)throw Error('Imagen mayor a 10 MB; reduce su tamaño.');chunks.push(chunk);}await writeFile(`${staging}/${id}.${ext}`,Buffer.concat(chunks));return `./generated/${id}.${ext}`;}
try{
const eventPages=await query(agenda),resourcePages=await query(materials),events=[],resources=[];
for(const page of eventPages){const e=eventFromPage(page);if(e){e.image=await image(page,e.id);events.push(e);}}
for(const page of resourcePages){const r=resourceFromPage(page);if(r)resources.push(r);}
events.sort((a,b)=>a.start.localeCompare(b.start)||a.id.localeCompare(b.id));resources.sort((a,b)=>a.title.localeCompare(b.title,'es'));
const result={version:1,source:'notion',updatedAt:new Date().toISOString(),events,resources};
await writeFile('public/data.next.json',JSON.stringify(result,null,2));await rm('public/generated',{recursive:true,force:true});await rename(staging,'public/generated');await rename('public/data.next.json','public/data.json');console.log(`Sincronización completa: ${events.length} actividades y ${resources.length} materiales públicos.`);
}catch(e){await rm(staging,{recursive:true,force:true});throw e;}
